org.gradle.jvmargs=-Xmx4G -XX:MaxMetaspaceSize=1G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError -XX:+UseParallelGC -XX:+TieredCompilation
# org.gradle.java.home=C\:/Users/markj/AppData/Roaming/.minecraft/runtime/java-runtime-delta/windows/java-runtime-delta
android.useAndroidX=true
android.enableJetifier=false
android.overridePathCheck=true
android.suppressUnsupportedCompileSdk=36
android.user.home=C\:\\Users\\markj\\.android
org.gradle.java.home=C\:\\Users\\markj\\.gradle\\jdks\\jetbrains_s_r_o_-21-amd64-windows.2
kotlin.incremental=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.vfs.watch=true
